# Deployment
apiVersion: apps/v1
kind: Deployment # Every kind has a different apiVersion (see line 2 and 15)
# Metadata
metadata:
  name: example-deployment
  labels:
    app: nginx # 1
# Specifications
spec:
  replicas: 2 # Amount of containers you want
  selector:    
    matchLabels:  # Pods get the label through the template blueprint
      app: nginx # matches the labels
  template:
    metadata:
      labels:
        app: nginx # 2
    # The specification inside of a template applies to a pod
    # The "spec" is also referred to as a blueprint for a pod
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8080
